[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]

[fuzz]
runs = 100
max_test_rejects = 1000000000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config